#Dockerfile.ollama
FROM ollama/ollama:latest

# Установка curl без фиксированной версии
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*